# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YRMImAPTXYaBZbaRJ-FDgVK98VsQ71FQ
"""



def find_url(text):
    return re.findall(r'https?://[^\s]+', text)

sentence = "I love spending time at https://www.xy123z.com/ "
print (find_url(sentence))

def extract_emails(text):
    return re.findall(r'\b[\w.-]+@[\w.-]+\.\w{2,4}\b', text)
sentence = "My email id is xyz111@gmail.com"
print (extract_emails(sentence))

def extract_hashtags(text):
    return re.findall(r'#\w+', text)

sentence = "#Sushant is trending now in the world."
print(extract_hashtags(sentence))

def extract_mentions(text):
    return re.findall(r'@\w+', text)
sentence = "@Ajit, please help me"
print(extract_mentions(sentence))

def extract_numbers(text):
    return re.findall(r'\d+', text)
sentence = "8853147 sq. km of area washed away in floods"
print (extract_numbers(sentence))

def extract_punctuations(text):
    return re.findall(r'[{}]'.format(re.escape(string.punctuation)), text)
sentence = "Corona virus killed #24506 people. #Corona is un(tolerable)"
print (extract_punctuations)